# Generated by Django 6.1 on 2026-08-29 06:41

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["receiver", "status"],
                        name="friends_fri_receive_dfe84a_idx",
                    ),
                    models.Index(
                        fields=["sender", "status"],
                        name="friends_fri_sender__5307d9_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("receiver")), _negated=True
                        ),
                        name="friendship_cannot_be_with_yourself",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.comparison.Least(
                            models.F("sender_id"), models.F("receiver_id")
                        ),
                        django.db.models.functions.comparison.Greatest(
                            models.F("sender_id"), models.F("receiver_id")
                        ),
                        name="unique_friendship_between_two_users",
                    ),
                ],
            },
        ),
    ]
