# Generated by Django 6.1 on 2026-09-03 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.UniqueConstraint(
                fields=("user", "started_at"),
                name="unique_study_session_per_user_and_start",
            ),
        ),
    ]
